### ISSUE TITLE
Ошибка на 4 шаге

### ISSUE THREAD

**Issue by bodryj** [regtime-ltd/certbot-dns-webnames#3]
manual-cleanup-hook command ../certbot-dns-webnames exists, but is not executable.

**Comment by linuxoid69** [comment]
как решил проблему ?

**Comment by alexmik** [comment]
> как решил проблему ?

сделать все скрипты в папке исполняемыми (chmod +x)

**Comment by linuxoid69** [comment]
Оказалось что у меня был не верно прописан путь до cleanup.sh
Видимо они не торопяться делать фиксы https://github.com/regtime-ltd/certbot-dns-webnames/pull/2/files
